global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "172.17.0.1:9093"

scrape_configs:
  - job_name: 'fastapi-v1'
    static_configs:
      - targets: ['172.17.0.1:8001']

  - job_name: 'fastapi-v2'
    static_configs:
      - targets: ['172.17.0.1:8002']

rule_files:
  - /etc/prometheus/alert.rules.yml